from tkinter import *
root = Tk()
root.title("loginApp")
root.geometry("400x400")
frame = Frame(master=root,height=200,width=360,bg="lightblue")
l1 = Label(frame,text="full name",bg="lightblue",fg="red",width=12)
l2 = Label(frame,text="Email ID",bg="lightblue",fg="red",width=12)
l3 = Label(frame,text="Password",bg="lightblue",fg="red",width=12)
name_entry = Entry(frame)
email_entry = Entry(frame)
password_entry = Entry(frame,show="*")
def display():
    name = name_entry.get()
    greet = "hey!"+name
    message = "\ncongradulations for your new account"
    textbox.insert(END,greet)
    textbox.insert(END,message)
textbox = Text(bg="yellow")
btn = Button(text="create account",command=display,bg="red",fg="white")
frame.place(x=20,y=0)
l1.place(x=20,y=20)
l2.place(x=20,y=80)
l3.place(x=20,y=140)
name_entry.place(x=150,y=20)
email_entry.place(x=150,y=80)
password_entry.place(x=150,y=140)
btn.place(x=130,y=210)
textbox.place(y=250)
root.mainloop()
